export const SIGNUP_CHANGE_VALIDATE = "SIGNUP_CHANGE_VALIDATE";
export const MAKE_CHANGE_SIGNUP = "MAKE_CHANGE_SIGNUP";
export const SUBMIT_DATA_SIGNUP = "SUBMIT_DATA_SIGNUP";
export const CLEAR_DATA_SIGNUP = "CLEAR_DATA_SIGNUP";
export const TOGGLE_SEEN = "TOGGLE_SEEN";
export const SEND_OTP = "SEND_OTP";
export const VERIFY_OTP = "VERIFY_OTP";

export const LOGIN_CHANGE_VALIDATE = "LOGIN_CHANGE_VALIDATE";
export const MAKE_CHANGE_LOGIN = "MAKE_CHANGE_LOGIN";
export const SUBMIT_DATA_LOGIN = "SUBMIT_DATA_LOGIN";
export const TOGGLE_SEEN_LOGIN = "TOGGLE_SEEN_LOGIN";
export const CLEAR_DATA_LOGIN = "CLEAR_DATA_LOGIN";

export const ON_CHANGE_SEARCH = "ON_CHANGE_SEARCH";
export const UPDATE_RECENT_TAB = "UPDATE_RECENT_TAB";
export const UPDATE_MSG_LIST = "UPDATE_MSG_LIST";
export const SEND_MSG = "SEND_MSG";
export const UPDATE_ONLINE = "UPDATE_ONLINE";
export const DELETE_CARD = "DELETE_CARD";
export const DELETE_MSG = "DELETE_MSG";
export const SET_SEARCH_LOADER = "SET_SEARCH_LOADER";

export const SET_MSG_BOOL = "SET_MSG_BOOL";

export const LOGOUT = "LOGOUT";
